### ISSUE TITLE
I can't download math books

### ISSUE THREAD

**Issue by VoltrY** [creeperkafasi/isler-kutuphane#1]

**Comment by creeperkafasi** [comment]
Could you provide more information on the steps to replicate your issue? It works fine for me. Make sure to follow the steps in the disclaimer if you are using a Chromium based browser.

**Comment by VoltrY** [comment]
I am using firefox browser. and when I press the math option of the site, no books appear.

**Comment by creeperkafasi** [comment]
Closing as cannot reproduce.
